"""The URD grammar, encoded as a recognizer.

A castle is written as ``U (tower) D``: the leading ``U`` and trailing ``D``
are the baseline block, and the interior is the *tower*, the skyline of the
castle above the base read left-to-right as a word over ``{U, R, D}``
(``U`` = up one row, ``R`` = right one column, ``D`` = down one row).

Towers of height at most ``k`` are generated by the grammar::

    E_k -> empty | R E_k | U V D (empty | R E_k)      V = E_{k-1}, V nonempty

* ``empty``            -- nothing above the base;
* ``R E_k``            -- one empty column, then the rest;
* ``U V D (empty|R E_k)`` -- a peak: up, a nonempty sub-tower of height at most
  ``k-1``, down, then stop or a gap column and the next peak.

The structural rules all fall out of this grammar: ``#U == #D`` (balance), no
``UD`` (the nonempty ``V`` forbids a zero-width block), no ``DU`` (the tail is
``empty | R E_k``, so peaks are separated by a gap), and exactly ``#R`` columns.

:func:`validate` is this grammar plus the even-block rule (``#D`` even), which
is *not* part of ``E_k`` -- ``E_k`` counts towers of every parity.
"""

from __future__ import annotations


class ParseError(ValueError):
    """Raised when a string is not a valid URD castle string."""


def _is_tower(word: str, k: int) -> bool:
    """True iff ``word`` is a tower word in ``E_k`` (height at most ``k``).

    A direct recursive-descent translation of the three productions.
    """
    if not word:
        return True  # E_k -> empty
    head = word[0]
    if head == "R":
        return _is_tower(word[1:], k)  # E_k -> R E_k
    if head == "U" and k > 0:
        # E_k -> U V D (empty | R E_k), V = E_{k-1} nonempty.
        for j in range(2, len(word) + 1):  # V = word[1:j], at least one char
            if _is_tower(word[1:j], k - 1) and j < len(word) and word[j] == "D":
                tail = word[j + 1 :]
                if tail == "":
                    return True
                if tail[0] == "R" and _is_tower(tail[1:], k):
                    return True
        return False
    return False


def is_tower(word: str) -> bool:
    """True iff ``word`` is a tower word of any height.

    ``len(word)`` is a safe height cap: a balanced word of length ``n`` has
    height at most ``n // 2``.
    """
    return _is_tower(word, len(word))


def is_castle_string(s: str) -> bool:
    """True iff ``s`` has the shape ``U (tower) D`` with a grammar-valid tower.

    Structural/encoding validity only -- the even-block rule is *not* checked.
    """
    if not isinstance(s, str):
        return False
    if len(s) < 2 or s[0] != "U" or s[-1] != "D":
        return False
    return is_tower(s[1:-1])


def validate(s: str) -> bool:
    """True iff ``s`` is a valid castle string.

    A castle string is ``U (tower) D`` with a grammar-generated tower, and an
    even number of ``D`` steps (each ``D`` completes a block, so ``#D`` is the
    total block count -- the Project Euler 502 even-block rule).
    """
    return is_castle_string(s) and s.count("D") % 2 == 0
