"""The URD grammar, encoded as a recognizer.

A castle is written as ``U (tower) D``: the leading ``U`` and trailing ``D``
are the baseline block, and the interior is the *tower*, the skyline of the
castle above the base read left-to-right as a word over ``{U, R, D}``
(``U`` = up one row, ``R`` = right one column, ``D`` = down one row).

Towers of height at most ``k`` are generated by the grammar::

    E_k -> empty | R E_k | U V D (empty | R E_k)      V = E_{k-1}, V nonempty

* ``empty``              -- nothing above the base;
* ``R E_k``              -- one empty column, then the rest;
* ``U V D (empty|R E_k)`` -- a peak: up, a nonempty sub-tower of height at most
  ``k-1``, down, then stop or a gap column and the next peak.

The structural rules all fall out of this grammar: ``#U == #D`` (balance), no
``UD`` (the nonempty ``V`` forbids a zero-width block), no ``DU`` (the tail is
``empty | R E_k``, so peaks are separated by a gap), and exactly ``#R`` columns.

:func:`validate` is this grammar plus the even-block rule (``#D`` even), which
is *not* part of ``E_k`` -- ``E_k`` counts towers of every parity.
"""

from __future__ import annotations


class ParseError(ValueError):
    """A precise reason a string is not a valid castle.

    ``reason`` is a short machine-readable code (e.g. ``"odd_blocks"``);
    ``message`` is human-readable.
    """

    def __init__(self, reason: str, message: str) -> None:
        self.reason = reason
        self.message = message
        super().__init__(message)

    def __repr__(self) -> str:
        return f"ParseError({self.reason!r}, {self.message!r})"


def _is_tower(word: str, k: int) -> bool:
    """True iff ``word`` is a tower word in ``E_k`` (height at most ``k``).

    A direct recursive-descent translation of the three productions.
    """
    if not word:
        return True  # E_k -> empty
    head = word[0]
    if head == "R":
        return _is_tower(word[1:], k)  # E_k -> R E_k
    if head == "U" and k > 0:
        # E_k -> U V D (empty | R E_k), V = E_{k-1} nonempty.
        for j in range(2, len(word) + 1):  # V = word[1:j], at least one char
            if _is_tower(word[1:j], k - 1) and j < len(word) and word[j] == "D":
                tail = word[j + 1 :]
                if tail == "":
                    return True
                if tail[0] == "R" and _is_tower(tail[1:], k):
                    return True
        return False
    return False


def is_tower(word: str) -> bool:
    """True iff ``word`` is a tower word of any height.

    ``len(word)`` is a safe height cap: a balanced word of length ``n`` has
    height at most ``n // 2``.
    """
    return _is_tower(word, len(word))


def _tower_diagnosis(word: str) -> ParseError:
    """Explain, in a human-friendly way, why ``word`` is not a tower word."""
    if any(c not in "URD" for c in word):
        bad = next(c for c in word if c not in "URD")
        return ParseError(
            "invalid_character", f"tower word contains {bad!r} (only U, R, D allowed)"
        )
    if "UD" in word:
        return ParseError("zero_width_block", "tower word contains a zero-width block (UD)")
    if "DU" in word:
        return ParseError("touching_blocks", "tower word contains two touching blocks (DU)")
    if word.count("U") != word.count("D"):
        return ParseError("unbalanced", "tower word has unequal numbers of U and D steps")
    height = 0
    for c in word:
        if c == "U":
            height += 1
        elif c == "D":
            height -= 1
        if height < 0:
            return ParseError("drops_below_base", "tower word drops below the base")
    return ParseError("invalid_tower", "tower word is not generated by the grammar")


def structural_error(s: object) -> ParseError | None:
    """A :class:`ParseError` if ``s`` is not ``U (tower) D``, else ``None``.

    Structural/encoding validity only -- the even-block rule is *not* checked.
    """
    if not isinstance(s, str):
        return ParseError("type_error", f"expected str, got {type(s).__name__}")
    if len(s) < 2 or s[0] != "U" or s[-1] != "D":
        return ParseError("not_castle_shape", "a castle string must be 'U' (tower) 'D'")
    tower = s[1:-1]
    if not is_tower(tower):
        return _tower_diagnosis(tower)
    return None


def is_castle_string(s: object) -> bool:
    """True iff ``s`` has the shape ``U (tower) D`` with a grammar-valid tower.

    Structural/encoding validity only -- the even-block rule is *not* checked.
    """
    return structural_error(s) is None


def validate(s: object) -> bool | ParseError:
    """``True`` if ``s`` is a valid castle string, else a :class:`ParseError`.

    A castle string is ``U (tower) D`` with a grammar-generated tower and an
    even number of ``D`` steps (each ``D`` completes a block, so ``#D`` is the
    total block count -- the Project Euler 502 even-block rule).  Callers test
    ``validate(s) is True``.
    """
    err = structural_error(s)
    if err is not None:
        return err
    assert isinstance(s, str)  # structural_error returned None
    if s.count("D") % 2 != 0:
        return ParseError("odd_blocks", "a castle must be made from an even number of blocks")
    return True
